In [14]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
import numpy as np

In [15]:
iris_data = load_iris()

In [16]:
X = iris_data['data']

Simply computes the following equation on a per feature basis
$$z = \frac{x - \mu}{\sigma}$$

In [17]:
Z = StandardScaler().fit_transform(X)

The covariance matrix is defined as:
$$ \frac{1}{n} (\textbf{X}-\mu_{x})^{T}(\textbf{X}-\mu_{x})$$
Where $n$ is the number of rows in the matrix.

In [20]:
# Just the above equation in code.
mean = np.mean(Z, axis=0)
covariance_matrix = (Z - mean).T.dot(Z - mean) / (Z.shape[0] - 1)

print(covariance_matrix)

[[ 1.00671141 -0.11010327  0.87760486  0.82344326]
 [-0.11010327  1.00671141 -0.42333835 -0.358937  ]
 [ 0.87760486 -0.42333835  1.00671141  0.96921855]
 [ 0.82344326 -0.358937    0.96921855  1.00671141]]


In [22]:
# Next we are going to find the eigenvectors 
# of the covariance matrix.
eigen_vals, eigen_vectors = np.linalg.eig(covariance_matrix)

print(eigen_vals)
print('')
print(eigen_vectors)

[ 2.93035378  0.92740362  0.14834223  0.02074601]

[[ 0.52237162 -0.37231836 -0.72101681  0.26199559]
 [-0.26335492 -0.92555649  0.24203288 -0.12413481]
 [ 0.58125401 -0.02109478  0.14089226 -0.80115427]
 [ 0.56561105 -0.06541577  0.6338014   0.52354627]]


In [25]:
# Sort the eigenvectors by their eigenvalues 
# (how much each eigenvector contributes to the 
# distribution of hte data)

# Pair the eigenvectors with their eigenvalue
eigen_pairs = [(np.abs(eigen_vals[i]), eigen_vectors[i]) for i in range(len(eigen_vals))]

sorted_eigen_pairs = sorted(eigen_pairs, key=lambda x: x[0], reverse=True)

for sorted_eigen_pair in sorted_eigen_pairs:
    print(sorted_eigen_pair)

(2.9303537755893165, array([ 0.52237162, -0.37231836, -0.72101681,  0.26199559]))
(0.92740362151734079, array([-0.26335492, -0.92555649,  0.24203288, -0.12413481]))
(0.14834222648163947, array([ 0.58125401, -0.02109478,  0.14089226, -0.80115427]))
(0.020746013995595794, array([ 0.56561105, -0.06541577,  0.6338014 ,  0.52354627]))


In [28]:
# Get the relative contribution of each eigenvector.
# This is called the explained variance
total = sum(eigen_vals)
explained_var = [(eigen_val / total) * 100 
                 for eigen_val, eigen_vec in sorted_eigen_pairs]
for explained_var_ele in explained_var:
    print("%.2f%%" % explained_var_ele)

72.77%
23.03%
3.68%
0.52%


In [33]:
# Finally construct the matrix to project the original data to
# the new space. In practice examine the explained variance to 
# determine the number of eigenvectors to select.
N = 2
proj_matrix = np.array([eigen_vec for eigen_val, eigen_vec in sorted_eigen_pairs[:N]]).T
print(proj_matrix)

[[ 0.52237162 -0.26335492]
 [-0.37231836 -0.92555649]
 [-0.72101681  0.24203288]
 [ 0.26199559 -0.12413481]]


In [36]:
X_proj = Z.dot(proj_matrix)
# The data now has dimensionality N.
print(X_proj[:5])

[[-0.2316583  -0.87967436]
 [ 0.07253025  0.25502854]
 [-0.18536908 -0.12326756]
 [-0.24451042  0.15034585]
 [-0.38110853 -1.06194072]]
